// 作者列表
export const SUCCESS_GET_USER_LIST = 'SUCCESS_GET_USER_LIST'
export const FAILURE_GET_USER_LIST = 'FAILURE_GET_USER_LIST'
export const SUCCESS_GET_USER_ADD_LIST = 'SUCCESS_GET_USER_ADD_LIST'

// 文章内容
export const SUCCESS_GET_CONTENT_DETAIL = 'SUCCESS_GET_CONTENT_DETAIL'
export const FAILURE_GET_CONTENT_DETAIL = 'FAILURE_GET_CONTENT_DETAIL'

export const SUCCESS_SAVE_CONTENT_DETAIL = 'SUCCESS_SAVE_CONTENT_DETAIL'
export const FAILURE_SAVE_CONTENT_DETAIL = 'FAILURE_SAVE_CONTENT_DETAIL'

// 更新组件数据
export const UPDATE_COMPONENT_DATA = 'UPDATE_COMPONENT_DATA'
export const CLEAR_COMPONENT_DATA = 'CLEAR_COMPONENT_DATA'