// 显示、隐藏选择文章弹窗
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS'
export const GET_ARTICLE_LIST_FAIL = 'GET_ARTICLE_LIST_FAIL'
export const GET_SELECT_ARTICLE_LIST = 'GET_SELECT_ARTICLE_LIST'
export const SHOW_SELECT_ARTICLE = 'SHOW_SELECT_ARTICLE'
